name: Update AI Digest Sheet

on:
  workflow_dispatch:        # manual trigger button
  schedule:
    - cron:  '0 14 * * *'   # runs 07:00 PT daily

jobs:
  run-script:
    runs-on: ubuntu-latest

    steps:
    - name: Check out repo
      uses: actions/checkout@v4

    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: '3.11'

    - name: Install deps
      run: |
        pip install -r requirements.txt

    - name: Write service account to disk
      env:
        GCP_JSON: ${{ secrets.GCP_SERVICE_ACCOUNT_JSON }}
      run: |
        echo "$GCP_JSON" > service_account.json

    - name: Run AI Digest
      env:
        GOOGLE_APPLICATION_CREDENTIALS: ${{ github.workspace }}/service_account.json
      run: |
        python ai_feed_generator.py
